@extends('layouts.master')
@section('content')
<section class="cta">
    <div class="container">
        <div class="row">
            <div class="panel panel-primary">
                <div class="panel-heading" style="font-family:Century Gothic;">
                    <b>Daffodil International University Awarded its Researchers at Research Award Giving Ceremony 2022</b>
                </div>
                <div class="panel-body">
                    <img src="{{url('images/event/six.jpg')}}" class="center">
                    <p style="font-family:Century Gothic; font-size: 15px; padding-top: 15px">To celebrate about 500 Scopus indexed research publications in 2021 and to recognize the scholarly contributions of the faculty members, students and alumni, the Division of Research of Daffodil International University organized the “Research Award Giving Ceremony 2022” on 23rd March, 2022 at the International Conference Hall of the university, Daffodil Smart City, Ashulia, Dhaka.</p>
                    <p style="font-family:Century Gothic; font-size: 15px;">Prof. Dr. Biswajit Chanda, Member, University Grants Commission of Bangladesh (UGC) was present at the program as the chief guest. The program was also addressed by Dr. Md. Sabur Khan, Chairman, Board of Trustees, DIU, Professor Dr. M. Lutfar Rahman, Vice Chancellor of DIU, Professor Dr. SM Mahbub Ul Haque Majumder, Pro Vice Chancellor of DIU and Prof. Dr. Md. Kabirul Islam, Director, Division of Research, DIU. Among others, Professor Dr. Engr. AKM Fazlul Hoque, Registrar, all Deans of Faculties, Head of the Departments and all Faculty members were present at the program. At the outset, Prof. Dr. Md. Kabirul Islam, Director, Division of Research delivered the welcome address and a presentation on DIU’s recent research achievements and declared the names of the special awardees based on the Scopus indexed quality publications in 2021.</p>
                    <p style="font-family:Century Gothic; font-size: 15px;">Prof. Dr. Kudrat-E-Khuda Babu, Head, Department of Law and Nurul Mohammad Zayed, Assistant Professor, Department of Business Administration individually achieved Best Research Award 2022 in recognition of their good number of publications in high indexed journals. Besides, two students of DIU: Md. Mominur Rahman, Department of Pharmacy and F.M. Javed Mehedi Shamrat, Department of Software Engineering were individually awarded the ‘Best Student Research Award 2022’.</p>
                    <p style="font-family:Century Gothic; font-size: 15px;">On the other hand, the Department of Public Health; Department of Pharmacy, Department of Business Administration achieved Best Department Research Award 2022 for their quality publications and research networking and Department of Computer Science & Engineering got the Best Department Research Award 2022 for involving the highest number of students in research and publications. The awardees received a certificate and financial incentives for their scholarly work.</p>
                    <p style="font-family:Century Gothic; font-size: 15px;">While addressing as the chief guest Prof. Dr. Biswajit Chanda said that the main feature of a complete university is to create new knowledge and research is considered to be the key component of a university. In this technological era, there is no alternative to become skilled in technology like AI and robotics. Daffodil University has the reputation as an IT based University of the Country.</p>
                    <p style="font-family:Century Gothic; font-size: 15px;">Research should not only be published but also benefit the people of the country and play a role in building the golden Bengal of the dream of the father of the nation, he added. He urged the researchers to conduct research activities not only with university funding, but also to increase collaboration with industry, foreign universities or to fund research with the help of international organizations. He called for conducting research to address the challenges of the future, taking into account issues such as artificial intelligence and the Fourth Industrial Revolution.</p>
                    <p style="font-family:Century Gothic; font-size: 15px;">Dr. Md. Sabur Khan in his speech focused on social and commercial impacts and branding. He urged the researchers to focus on getting patents for their intellectual innovation and research work. He requested UGC to work with the government to consider the possibility of authorizing capable private universities to award PhD degrees by fixing relevant KPI to ensure quality and capability.</p>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection